services:
  terraform:
    image: hashicorp/terraform
    container_name: terraform
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - ~/.aws:/root/.aws
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
