services:
  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5433:5432"
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - dbt-network


  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - ./.env
      - ./datawarehouse/.env
    environment:
      DBT_PROFILES_DIR: /PROJECT/datawarehouse
      DBT_PROJECT_DIR: /PROJECT/datawarehouse
      PYTHONPATH: ${PROJECT_PATH}/api:${PROJECT_PATH}/datawarehouse:${PROJECT_PATH}/shared:${PROJECT_PATH}/app:${PROJECT_PATH}
      PROJECT_PATH: ${PROJECT_PATH}
      DBT_PATH: ${PROJECT_PATH}/datawarehouse
    ports:
    - "8080:8080"
    - "8200:8200"
    - "8210:8210"
    volumes:
    - ./:${PROJECT_PATH}
    networks:
      - dbt-network
    depends_on:
      - postgres
    command: "sh ./execute.sh"


  pgadmin:
    image: elestio/pgadmin:REL-8_12
    container_name: pgadmin
    restart: always
    env_file:
      - ./.env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
    - "5050:80"
    volumes:
    - pgadmin-cache:/var/lib/pgadmin
    networks:
      - dbt-network
    depends_on:
      - postgres

  mkdocs:
    build:
      context: ./
      dockerfile: Dockerfile.mkdocs
    container_name: mkdocs
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./:/docs
    networks:
      - dbt-network

volumes:
  db-data:
    driver: local
  pgadmin-cache:
    driver: local

networks:
  dbt-network:
    driver: bridge