services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - ./.env
      - ./datawarehouse/.env
    environment:
      DB_URL: ${DB_URL_PROD}
      DBT_PROFILES_DIR: /PROJECT/datawarehouse
      DBT_PROJECT_DIR: /PROJECT/datawarehouse
      PYTHONPATH: ${PROJECT_PATH}/api:${PROJECT_PATH}/datawarehouse:${PROJECT_PATH}/shared:${PROJECT_PATH}/app:${PROJECT_PATH}
      PROJECT_PATH: ${PROJECT_PATH}
      DBT_PATH: ${PROJECT_PATH}/datawarehouse
    ports:
    - "8080:8080"
    - "8200:8200"
    - "8210:8210"
    volumes:
    - ./:${PROJECT_PATH}
    networks:
      - dbt-network
    command: "sh ./execute.sh"

  mkdocs:
    build:
      context: ./
      dockerfile: Dockerfile.mkdocs
    container_name: mkdocs
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./:/docs
    networks:
      - dbt-network

volumes:
  db-data:
    driver: local
  pgadmin-cache:
    driver: local

networks:
  dbt-network:
    driver: bridge